IF NOT EXISTS (SELECT * FROM sys.databases where name = 'Scorched')
BEGIN
	CREATE DATABASE Scorched
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA ='dbo' AND TABLE_NAME = 'accounts')
BEGIN
	CREATE TABLE accounts (ID int IDENTITY(1,1) PRIMARY KEY,NAME varchar(255),PASSWORD varchar(255),last_logged varchar(255))
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA ='dbo' AND TABLE_NAME = 'characters')
BEGIN
	CREATE TABLE characters (ID int IDENTITY(1,1) PRIMARY KEY,NAME varchar(255),X int,Y int,Z int,DIRECTION int,STEP int,AIM_DIRECTION int,SPRITE int)
END