USE master;
GO
IF DB_ID('SCORCHED') IS NULL
CREATE DATABASE SCORCHED;
GO
USE SCORCHED;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ACCOUNTS')
CREATE TABLE ACCOUNTS (ID int IDENTITY(1,1) PRIMARY KEY,NAME VARCHAR(255),PASSWORD VARCHAR(255),last_logged varchar(255));
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CHARACTERS') 
CREATE TABLE CHARACTERS (ID int IDENTITY(1,1) PRIMARY KEY,NAME VARCHAR(255),X int,Y int,Z int,DIRECTION int,STEP int,AIM_DIRECTION int,SPRITE int);
