USE SCORCHED;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VERSION')
BEGIN
	CREATE TABLE VERSION (VERSION VARCHAR(255), BUILD VARCHAR(255), RELEASE_DATE VARCHAR(255));
END
GO
IF NOT EXISTS (SELECT 1 FROM dbo.VERSION)
BEGIN
	INSERT INTO dbo.VERSION (VERSION,BUILD,RELEASE_DATE) VALUES('1','1',(SELECT FORMAT(CURRENT_TIMESTAMP, 'yyyy-dd-MM HH:mm:ss.fff', 'en-US')))
END