USE SCORCHED;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VERSION')
BEGIN
	CREATE TABLE VERSION (VERSION VARCHAR(255), BUILD VARCHAR(255), RELEASE_DATE VARCHAR(255));
END
GO
IF NOT EXISTS (SELECT 1 FROM dbo.VERSION)
BEGIN
	DECLARE @today DATETIME = SYSDATETIME();
	INSERT INTO dbo.VERSION (VERSION,BUILD,RELEASE_DATE) VALUES('1','1',(SELECT CONVERT(VARCHAR(50), @today, 121)))
END