USE SCORCHED;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VERSION') 
CREATE TABLE VERSION (VERSION VARCHAR(255), BUILD VARCHAR(255), RELEASE_DATE VARCHAR(255));
GO
INSERT INTO dbo.VERSION
(
    VERSION,
    BUILD,
    RELEASE_DATE
)
VALUES
(   '1', -- VERSION - varchar(255)
    '1', -- BUILD - varchar(255)
     CURRENT_TIMESTAMP -- RELEASE_DATE - varchar(255)
    )