USE SCORCHED;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ACCOUNTS')
BEGIN
CREATE TABLE ACCOUNTS (ID int IDENTITY(1,1) PRIMARY KEY NOT NULL,NAME VARCHAR(255) NOT NULL,PASSWORD VARCHAR(255) NOT NULL,LAST_LOGIN varchar(255) NOT NULL,CHAR_1 INT NOT NULL, CHAR_2 INT NOT NULL, CHAR_3 INT NOT NULL, CHAR_4 INT NOT NULL, CHAR_5 INT NOT NULL);
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CHARACTERS') 
BEGIN
CREATE TABLE CHARACTERS (ID int IDENTITY(1,1) PRIMARY KEY NOT NULL,NAME VARCHAR(255) NOT NULL,X INT NOT NULL,Y INT NOT NULL,Z INT NOT NULL,DIRECTION INT NOT NULL,STEP INT NOT NULL,AIM_DIRECTION INT NOT NULL,SPRITE INT NOT NULL);
END